// ============================================================
// ADAPTERS — each has a REAL path (used when its key is set in
// config.js) and a MOCK path (sample data, used until then).
// The pipeline never knows the difference.
// ============================================================
const cfg = require("./config");
const { kfetch } = require("./khttp");

const aiProvider = cfg.ANTHROPIC_API_KEY ? "Anthropic" : cfg.OPENAI_API_KEY ? "OpenAI" : null;
const mode = {
  ai: aiProvider ? "REAL" : "MOCK",
  aiProvider: aiProvider || "sample data",
  anthropic: aiProvider ? "REAL" : "MOCK", // back-compat alias
  kit: (cfg.KIT_API_KEY || cfg.KIT_API_SECRET) ? "REAL" : (cfg.KIT_API_V3_KEY ? "REAL (read-only — add KIT_API_SECRET to schedule)" : "MOCK"),
  libsyn: cfg.LIBSYN_CLIENT_ID ? "REAL" : "MOCK",
  slack: cfg.SLACK_WEBHOOK_URL ? "REAL" : "MOCK",
};

// ---------------- AI WRITING (Anthropic preferred, OpenAI fallback) ----------------
async function aiGenerate(system, user, maxTokens) {
  if (aiProvider === "Anthropic") {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": cfg.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: cfg.ANTHROPIC_MODEL,
        max_tokens: maxTokens || 4000,
        system,
        messages: [{ role: "user", content: user }],
      }),
    });
    if (!res.ok) throw new Error("Anthropic API " + res.status + ": " + (await res.text()));
    const data = await res.json();
    return data.content.map((c) => c.text || "").join("\n");
  }
  if (aiProvider === "OpenAI") {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        authorization: "Bearer " + cfg.OPENAI_API_KEY,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: cfg.OPENAI_MODEL,
        max_tokens: maxTokens || 4000,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
    });
    if (!res.ok) throw new Error("OpenAI API " + res.status + ": " + (await res.text()));
    const data = await res.json();
    return data.choices[0].message.content;
  }
  // MOCK: deterministic sample output so the pipeline is fully demonstrable
  return null; // callers provide their own mock builder
}

function mockShownotes(ep) {
  const g = ep.guest ? ` with guest ${ep.guest}` : "";
  return (
    `EPISODE DESCRIPTION\n` +
    `In this episode of the Thriving Dentist Show${g}, we dig into "${ep.title}". ` +
    `You will hear the exact numbers, the schedule changes, and the first step to try this in your own practice this month. ` +
    `If production feels stuck while the team feels stretched, this conversation shows a way out that does not mean working more days.\n\n` +
    `TIMESTAMPS\n02:14 — Why the old schedule was capping production\n08:40 — The block-scheduling rebuild, step by step\n15:22 — The 90-day numbers\n21:05 — What the team said\n27:30 — The first thing to measure before changing anything\n\n` +
    `KEY TAKEAWAYS\n• Measure hourly production per column for 30 days before touching the schedule\n• Two production columns beat five chaotic ones\n• Fixed hygiene windows stop same-day chaos\n• Retention improves when the schedule respects the team\n• A shorter week can produce more, not less\n\n` +
    `SEO TITLE TAG\n${ep.title.slice(0, 57)}\n\nMETA DESCRIPTION\nHow one practice grew production 22% on a shorter week — the schedule rebuild, the numbers, and where to start.\n\n` +
    `CTA\nReady to find the growth hiding in your practice? Book a free Marketing Strategy Meeting: ${cfg.MSM_LINK}\nPrefer a clinical-side conversation? ${cfg.CSM_LINK}\n\n[SAMPLE OUTPUT — generated by MOCK adapter. Add ANTHROPIC_API_KEY in config.js for real generation.]`
  );
}

function mockNewsletter(ep, kind) {
  const weekend = kind === "weekend";
  return (
    `SUBJECT: ${weekend ? "The 4-day week your team keeps asking about" : "New episode: " + ep.title}\n` +
    `PREHEADER: The numbers behind a shorter, stronger week.\n\n` +
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center">\n` +
    `<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="font-family:Georgia,serif;color:#1E2B33">\n` +
    `<tr><td style="padding:24px">\n` +
    `<p style="font-size:18px;font-weight:bold">${weekend ? "It is the weekend. Perfect time for this one." : "Your schedule might be the ceiling."}</p>\n` +
    `<p>This week on the Thriving Dentist Show: <b>${ep.title}</b>${ep.guest ? " with " + ep.guest : ""}.</p>\n` +
    `<p>Flat production. A tired team. Sound familiar? This episode walks through the schedule rebuild that changed both — with the real numbers.</p>\n` +
    `<ul><li>The 30-day measurement to do first</li><li>The block-schedule rebuild</li><li>The 90-day results</li></ul>\n` +
    `<p><a href="${ep.link || "#"}" style="background:#136572;color:#fff;padding:12px 22px;text-decoration:none;border-radius:5px">Listen to the episode</a></p>\n` +
    `<p style="border-top:1px solid #ddd;padding-top:14px">Want this kind of growth mapped for your practice? The Marketing Strategy Meeting is free: <a href="${cfg.MSM_LINK}">book a time here</a>.</p>\n` +
    `<p>— The Thriving Dentist team</p>\n` +
    `</td></tr></table></td></tr></table>\n\n[SAMPLE ${kind.toUpperCase()} HTML — MOCK adapter. Add ANTHROPIC_API_KEY for real generation.]`
  );
}

function mockLeadDraft(lead, ep) {
  const nm = /^dr/i.test(lead.name) ? "Dr. " + lead.name.split(" ").pop() : lead.name.split(" ")[0];
  return `Hi ${nm} — noticed you checked out the ${lead.link} from this week's episode ${ep.ep}. If that topic is live for your practice right now, happy to set up a quick time to talk it through. No pitch — just the strategy conversation.`;
}

// ---------------- KIT (email platform) ----------------
async function kitScheduleBroadcast(ep, kind, html, sendAt) {
  let subject = (html.match(/^SUBJECT:\s*(.+)$/m) || [])[1] || `TD EP ${ep.ep} — ${kind}`;
  // Safety prefix: forces a conscious human edit inside Kit before any send.
  subject = '[REVIEW BEFORE SEND] ' + subject;
  const htmlBody = html.slice(html.indexOf("<"));
  try {
    if (cfg.KIT_API_KEY) {
      // Kit v4: create a broadcast (draft) with scheduled send time.
      // DRAFT ONLY — no send_at, ever. The system never sends or schedules an
      // email by itself; a human sets the audience and schedules inside Kit.
      const res = await kfetch("https://api.kit.com/v4/broadcasts", {
        method: "POST",
        headers: { "X-Kit-Api-Key": cfg.KIT_API_KEY, "content-type": "application/json" },
        body: JSON.stringify({ subject, content: htmlBody }),
      });
      if (!res.ok) throw new Error("Kit v4 " + res.status + ": " + (await res.text()).slice(0, 200));
      const data = await res.json();
      return { id: data.broadcast?.id || "kit-v4", sendAt };
    }
    if (cfg.KIT_API_SECRET) {
      // Kit v3: create broadcast as a DRAFT (public:false, no send_at) so a human
      // confirms audience filters (TD tags + exclude Cold Subscribers) in Kit
      // before it is scheduled — per the Kit SOP.
      const res = await kfetch("https://api.convertkit.com/v3/broadcasts", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ api_secret: cfg.KIT_API_SECRET, subject, content: htmlBody, public: false }),
      });
      if (!res.ok) throw new Error("Kit v3 " + res.status + ": " + (await res.text()).slice(0, 200));
      const data = await res.json();
      return { id: data.broadcast?.id || "kit-v3-draft", sendAt, draft: true, note: "Created as DRAFT in Kit — set audience (TD tags, exclude Cold Subscribers) and schedule inside Kit." };
    }
    if (cfg.KIT_API_V3_KEY) {
      return { id: "PENDING-NEEDS-SECRET", sendAt, note: "v3 API Key connected (read-only). Add KIT_API_SECRET in config.js to create the broadcast in Kit automatically." };
    }
  } catch (err) {
    return { id: "KIT-ERROR", sendAt, error: err.message };
  }
  return { id: "mock-kit-" + kind + "-" + ep.ep, sendAt, mock: true };
}

async function kitGetClickers(ep) {
  // Real leads = people who clicked a SENT broadcast. Drafts have no clicks,
  // so until an episode newsletter actually sends, there is nothing to pull.
  // (Per-subscriber click pull gets wired against the first real send.)
  return [];
}

// ---------------- LIBSYN (podcast host) ----------------
async function libsynVerifyLive(ep) {
  // No API needed for the live check — the public episode/website URL tells the truth.
  const url = ep.liveUrl || ep.link || `https://www.thrivingdentist.com/?s=${encodeURIComponent(ep.title)}`;
  try {
    const res = await fetch(url, { method: "GET", redirect: "follow" });
    return { live: res.ok, status: res.status, url, checked: "public URL" };
  } catch (err) {
    return { live: false, status: 0, url, error: err.message, checked: "public URL" };
  }
}

async function libsynGetDownloads(ep) {
  if (mode.libsyn === "REAL") {
    throw new Error("Libsyn stats: wire api.libsyn.com endpoints once credentials are added");
  }
  return null; // no invented numbers — real downloads require Libsyn API access
}

// ---------------- SLACK (approvals + digest) ----------------
async function slackNotify(text) {
  if (mode.slack === "REAL") {
    await fetch(cfg.SLACK_WEBHOOK_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ text }),
    });
    return { sent: true };
  }
  return { sent: false, mock: true }; // surfaced in the in-app activity feed instead
}

module.exports = {
  mode, aiGenerate, mockShownotes, mockNewsletter, mockLeadDraft,
  kitScheduleBroadcast, kitGetClickers, libsynVerifyLive, libsynGetDownloads, slackNotify,
};
